name: Scheduled API Health Check

on:
  schedule:
    # Run every day at 9 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  health-check:
    name: API Health Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run API tests
        run: npm test
        continue-on-error: true
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scheduled-test-results-${{ github.run_number }}
          path: test-results/
          retention-days: 7
      
      - name: Notify on failure
        if: failure()
        run: |
          echo "⚠️ API health check failed!" >> $GITHUB_STEP_SUMMARY
          echo "Check the test results for details." >> $GITHUB_STEP_SUMMARY

